"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var excercise1_1 = require("./excercise1");
// let point = new Point(2,3);
// point.draw();
var likeFeature = new excercise1_1.LikeFeature(12, false);
console.log("Initial Like: " + likeFeature.likes + ", IsSelected: " + likeFeature.state);
console.log('Press Like BUtton');
likeFeature.onClick();
console.log("Current Like : " + likeFeature.likes + ", IsSelected: " + likeFeature.state);
